/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package elgamal;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Random;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import org.apache.poi.xwpf.extractor.XWPFWordExtractor;
import org.apache.poi.xwpf.usermodel.XWPFDocument;
import org.apache.poi.xwpf.usermodel.XWPFParagraph;
import org.apache.poi.xwpf.usermodel.XWPFRun;

/**
 *
 * @author lyhai
 */
public class Elgamal extends javax.swing.JFrame {

    /**
     * Creates new form Elgamal
     */
    public Elgamal() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtP = new javax.swing.JTextField();
        txtAlpha = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtA = new javax.swing.JTextField();
        txtBeta = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtK = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        btnTaoKhoa = new javax.swing.JButton();
        btnAuto = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        txtBanRo1 = new javax.swing.JTextField();
        btnMaHoa = new javax.swing.JButton();
        btnXoaBanRo = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        txtBanMa1 = new javax.swing.JTextField();
        btnGuiBanMa = new javax.swing.JButton();
        btnLuuBanMa = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        txtBanMa2 = new javax.swing.JTextField();
        btnGiaiMa = new javax.swing.JButton();
        btnXoaBanMa = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        txtBanRo2 = new javax.swing.JTextField();
        btnLuuBanRo = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jButton13 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Khóa công khai: ");

        jLabel2.setText("p: ");

        jLabel3.setText("Alpha:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Khóa bí mật:");

        txtP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPActionPerformed(evt);
            }
        });

        txtAlpha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAlphaActionPerformed(evt);
            }
        });

        jLabel5.setText("a:");

        txtA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAActionPerformed(evt);
            }
        });

        txtBeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBetaActionPerformed(evt);
            }
        });

        jLabel6.setText("Beta:");

        txtK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKActionPerformed(evt);
            }
        });

        jLabel7.setText("k:");

        btnTaoKhoa.setText("Tạo khóa");
        btnTaoKhoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTaoKhoaActionPerformed(evt);
            }
        });

        btnAuto.setText("Tạo khóa tự động");
        btnAuto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAutoActionPerformed(evt);
            }
        });

        btnXoa.setText("Xóa hết dữ liệu");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        jSeparator1.setForeground(new java.awt.Color(255, 51, 51));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Mã hóa:");

        jButton4.setText("Chọn file mã hóa");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setText("Bản rõ:");

        txtBanRo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBanRo1ActionPerformed(evt);
            }
        });

        btnMaHoa.setText("Mã hóa");
        btnMaHoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMaHoaActionPerformed(evt);
            }
        });

        btnXoaBanRo.setText("Xóa bản rõ");
        btnXoaBanRo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaBanRoActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setText("Bản mã:");

        txtBanMa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBanMa1ActionPerformed(evt);
            }
        });

        btnGuiBanMa.setText("Gửi bản mã");
        btnGuiBanMa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuiBanMaActionPerformed(evt);
            }
        });

        btnLuuBanMa.setText("Lưu bản mã");
        btnLuuBanMa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuBanMaActionPerformed(evt);
            }
        });

        jSeparator2.setForeground(new java.awt.Color(255, 51, 51));
        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setText("Bản mã:");

        btnGiaiMa.setText("Giải mã");
        btnGiaiMa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGiaiMaActionPerformed(evt);
            }
        });

        btnXoaBanMa.setText("Xóa bản mã");
        btnXoaBanMa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaBanMaActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setText("Bản rõ:");

        btnLuuBanRo.setText("Lưu bản rõ");
        btnLuuBanRo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuBanRoActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setText("Giải mã:");

        jButton13.setText("Chọn file giải mã");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtK, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtBeta, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtA, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabel4)
                                .addComponent(jLabel1)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtP, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtAlpha, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(btnTaoKhoa))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnAuto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnXoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(30, 30, 30)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnMaHoa, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnXoaBanRo))
                    .addComponent(txtBanRo1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtBanMa1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnGuiBanMa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnLuuBanMa))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(41, 41, 41)
                                .addComponent(jButton4))
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(12, 12, 12)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnGiaiMa, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnXoaBanMa))
                            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtBanMa2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtBanRo2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(41, 41, 41)
                                .addComponent(jButton13))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(btnLuuBanRo)))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(jButton13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addComponent(txtBanMa2, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnXoaBanMa)
                            .addComponent(btnGiaiMa))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel12)
                        .addGap(18, 18, 18)
                        .addComponent(txtBanRo2, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnLuuBanRo))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(27, 27, 27)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addGap(24, 24, 24)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel2)
                                        .addComponent(txtP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(23, 23, 23)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel3)
                                        .addComponent(txtAlpha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel4)
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel5)
                                        .addComponent(txtA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(17, 17, 17)
                                    .addComponent(btnTaoKhoa)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel6)
                                        .addComponent(txtBeta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel7)
                                        .addComponent(txtK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(18, 18, 18)
                                    .addComponent(btnAuto)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnXoa))
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel8)
                                        .addComponent(jButton4))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jLabel9)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtBanRo1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(btnXoaBanRo)
                                        .addComponent(btnMaHoa, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel10)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtBanMa1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnLuuBanMa)
                                        .addComponent(btnGuiBanMa)))))))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
   
    private boolean CheckSNT(long n) {
        if (n < 2) {
            return false;
        }
        for (long i = 2; i <= Math.sqrt(n); i++) {
            if (n % i == 0) {
                return false;
            }
        }
        return true;
    }
    
    private long BinhPhuongNhan (long a, long b, long x){
        long result = 1;
        a = a % x;
        while(b > 0){
            if (b % 2 == 1){
                result = (result*a) % x;
            }
            a = (a*a) %x;
            b = b / 2;
        }
        return result;
    }
    private void saveToDocxBanRo(File file) {
    XWPFDocument document = new XWPFDocument();
    XWPFParagraph paragraph = document.createParagraph();
    XWPFRun run = paragraph.createRun();
    String content = txtBanRo2.getText();
    run.setText(content);

    try {
        FileOutputStream fos = new FileOutputStream(file);
        document.write(fos);
        fos.close();
        document.close();
    } catch (IOException e) {
        e.printStackTrace();
    }
}
      private void saveToDocxBanMa(File file) {
    XWPFDocument document = new XWPFDocument();
    XWPFParagraph paragraph = document.createParagraph();
    XWPFRun run = paragraph.createRun();
    String content = txtBanMa1.getText();
    run.setText(content);

    try {
        FileOutputStream fos = new FileOutputStream(file);
        document.write(fos);
        fos.close();
        document.close();
    } catch (IOException e) {
        e.printStackTrace();
    }
}
    
    private void saveToTxtBanMa(File file) {
    String content = txtBanMa1.getText();
    try {
        BufferedWriter writer = new BufferedWriter(new FileWriter(file));
        writer.write(content);
        writer.close();
    } catch (IOException e) {
        e.printStackTrace();
    }
}
     private void saveToTxtBanRo(File file) {
    String content = txtBanRo2.getText();
    try {
        BufferedWriter writer = new BufferedWriter(new FileWriter(file));
        writer.write(content);
        writer.close();
    } catch (IOException e) {
        e.printStackTrace();
    }
}

    private void txtPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPActionPerformed

    private void txtAlphaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAlphaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAlphaActionPerformed

    private void txtAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAActionPerformed

    private void txtBetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBetaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBetaActionPerformed

    private void txtKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKActionPerformed

    private void txtBanRo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBanRo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBanRo1ActionPerformed

    private void btnTaoKhoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTaoKhoaActionPerformed
        if (txtP.getText().equals("") || txtAlpha.getText().equals("")||txtA.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Vui long nhap day du thong tin");
        }
        else{
        long p = Long.parseLong(txtP.getText());
        if (CheckSNT(p)){
            long alpha = Long.parseLong(txtAlpha.getText());
            long a = Long.parseLong(txtA.getText());
            long beta = BinhPhuongNhan(alpha, a, p);
            txtBeta.setText(beta+"");
            Random random = new Random();
            long k = random.nextLong((p - 2) + 1);
            txtK.setText("" + k);
        }
        else{
            JOptionPane.showMessageDialog(this, "Vui long nhap P la SNT");
            }
        }
    }//GEN-LAST:event_btnTaoKhoaActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
  JFileChooser fileChooser = new JFileChooser();
    FileNameExtensionFilter filter = new FileNameExtensionFilter("Documents (*.docx, *.txt)", "docx", "txt");
    fileChooser.setFileFilter(filter);

    long returnValue = fileChooser.showOpenDialog(null);
    if (returnValue == JFileChooser.APPROVE_OPTION) {
        File selectedFile = fileChooser.getSelectedFile();
        try {
            String fileContent = "";
            if (selectedFile.getName().endsWith(".docx")) {
                FileInputStream fis = new FileInputStream(selectedFile.getAbsolutePath());
                XWPFDocument document = new XWPFDocument(fis);
                XWPFWordExtractor extractor = new XWPFWordExtractor(document);
                fileContent = extractor.getText();
                extractor.close();
                fis.close();
            } else if (selectedFile.getName().endsWith(".txt")) {
                BufferedReader br = new BufferedReader(new FileReader(selectedFile.getAbsolutePath()));
                String line;
                while ((line = br.readLine()) != null) {
                    fileContent += line + "\n";
                }
                br.close();
            }

            txtBanRo1.setText(fileContent);
        } catch (IOException e) {
            e.printStackTrace();
        }
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        txtA.setText("");  
        txtAlpha.setText("");
        txtBanMa1.setText("");
        txtBanMa2.setText("");
        txtBanRo1.setText("");
        txtBanRo2.setText("");
        txtBeta.setText("");
        txtK.setText("");
        txtP.setText("");
        txtP.requestFocus();
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnAutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAutoActionPerformed
        Random random = new Random();
        long max = 60000, min = 400;
        long p, a, alpha, beta, k;
        do {
            p = random.nextLong((max - min) + 1) + min;
        } while (CheckSNT(p) == false);
         alpha = random.nextLong((p - 1) + 1) + 1;
         k = random.nextLong((p - 2) + 1);
         a = random.nextLong((p - 2) + 1) + 2;
         beta = BinhPhuongNhan(alpha, a, p);
         txtP.setText(p+"");
         txtA.setText(a+"");
         txtAlpha.setText(alpha+"");
         txtK.setText(k+"");
         txtBeta.setText(beta+"");
    }//GEN-LAST:event_btnAutoActionPerformed

    private void btnMaHoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMaHoaActionPerformed
        if (txtA.getText().equals("")||txtAlpha.getText().equals("")||txtBeta.getText().equals("")||
                txtK.getText().equals("")|| txtP.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Vui lòng nhập đủ thông tin các trường");
        }
        else{       
            String banRo = txtBanRo1.getText();
            long p = Long.parseLong(txtP.getText());
            long alpha = Long.parseLong(txtAlpha.getText());
            long k = Long.parseLong(txtK.getText());
            long beta = Long.parseLong(txtBeta.getText());
            long y = BinhPhuongNhan(alpha, k, p);
            //Tao bien tim gia tri lon nhat cua ban ro 
            long max = 0, temp;
            for (int i = 0; i < banRo.length(); i++) {
                temp = (long) banRo.charAt(i);
                if (temp > max) {
                    max = temp;
                }
            }
            if (p < max){
                JOptionPane.showMessageDialog(this, "Vui lòng nhập p là SNT và lớn hơn " + max);
                } 
            else{   
                ArrayList<Long> arrayBanMa = new ArrayList<>();
                for (int i = 0; i < banRo.length(); i++){
                    long gama =(banRo.charAt(i) % p)*BinhPhuongNhan(beta, k, p) % p;
                    arrayBanMa.add(y);
                    arrayBanMa.add(gama);
                    }
                String banMa = "";
                for (int i = 0; i < arrayBanMa.size(); i++){
                    long c = arrayBanMa.get(i);
                    banMa += (char)c;
                    }
                txtBanMa1.setText(banMa);
                }
            }
        
    }//GEN-LAST:event_btnMaHoaActionPerformed

    private void btnXoaBanRoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaBanRoActionPerformed
        txtBanRo1.setText("");
    }//GEN-LAST:event_btnXoaBanRoActionPerformed

    private void btnGuiBanMaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuiBanMaActionPerformed
        txtBanMa2.setText(txtBanMa1.getText());
    }//GEN-LAST:event_btnGuiBanMaActionPerformed

    private void btnXoaBanMaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaBanMaActionPerformed
        txtBanMa2.setText("");
    }//GEN-LAST:event_btnXoaBanMaActionPerformed

    private void btnGiaiMaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGiaiMaActionPerformed
        String banMa = txtBanMa2.getText();
        long a = Long.parseLong(txtA.getText());
        long p = Long.parseLong(txtP.getText());
        long alpha = Long.parseLong(txtAlpha.getText());

        ArrayList <Long> banRoArrayList = new ArrayList<>();
        for (int i = 1; i < banMa.length(); i+=2){
            char c = banMa.charAt(i);
            banRoArrayList.add((long)c);
        }
        long y = banMa.charAt(0);
        long y1 = BinhPhuongNhan(y, p-1-a, p);
        String banRo = "";
        for (int i = 0; i < banRoArrayList.size(); i++){
            long r = y1 * banRoArrayList.get(i) % p;
            banRo+= (char) r;
        }
        txtBanRo2.setText(banRo);
    }//GEN-LAST:event_btnGiaiMaActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
          JFileChooser fileChooser = new JFileChooser();
    FileNameExtensionFilter filter = new FileNameExtensionFilter("Documents (*.docx, *.txt)", "docx", "txt");
    fileChooser.setFileFilter(filter);

    int returnValue = fileChooser.showOpenDialog(null);
    if (returnValue == JFileChooser.APPROVE_OPTION) {
        File selectedFile = fileChooser.getSelectedFile();
        try {
            String fileContent = "";
            if (selectedFile.getName().endsWith(".docx")) {
                FileInputStream fis = new FileInputStream(selectedFile.getAbsolutePath());
                XWPFDocument document = new XWPFDocument(fis);
                XWPFWordExtractor extractor = new XWPFWordExtractor(document);
                fileContent = extractor.getText();
                extractor.close();
                fis.close();
            } else if (selectedFile.getName().endsWith(".txt")) {
                BufferedReader br = new BufferedReader(new FileReader(selectedFile.getAbsolutePath()));
                String line;
                while ((line = br.readLine()) != null) {
                    fileContent += line + "\n";
                }
                br.close();
            }

            txtBanMa2.setText(fileContent);
        } catch (IOException e) {
            e.printStackTrace();
        }
        }   // TODO add your handling code here:
    }//GEN-LAST:event_jButton13ActionPerformed

    private void btnLuuBanMaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuBanMaActionPerformed

    JFileChooser fileChooser = new JFileChooser();
    FileNameExtensionFilter filter = new FileNameExtensionFilter("Documents (*.docx, *.txt)", "docx", "txt");
    fileChooser.setFileFilter(filter);

    int returnValue = fileChooser.showSaveDialog(null);
    if (returnValue == JFileChooser.APPROVE_OPTION) {
        File selectedFile = fileChooser.getSelectedFile();
        String fileName = selectedFile.getAbsolutePath();
        if (selectedFile.getName().endsWith(".docx")) {
            if (!fileName.toLowerCase().endsWith(".docx")) {
                fileName += ".docx";
            }
            saveToDocxBanMa(new File(fileName));
        } else if (selectedFile.getName().endsWith(".txt")) {
            if (!fileName.toLowerCase().endsWith(".txt")) {
                fileName += ".txt";
            }
            saveToTxtBanMa(new File(fileName));
        }
    }
    }//GEN-LAST:event_btnLuuBanMaActionPerformed

    private void btnLuuBanRoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuBanRoActionPerformed

 JFileChooser fileChooser = new JFileChooser();
    FileNameExtensionFilter filter = new FileNameExtensionFilter("Documents (*.docx, *.txt)", "docx", "txt");
    fileChooser.setFileFilter(filter);

    int returnValue = fileChooser.showSaveDialog(null);
    if (returnValue == JFileChooser.APPROVE_OPTION) {
        File selectedFile = fileChooser.getSelectedFile();
        String fileName = selectedFile.getAbsolutePath();
        if (selectedFile.getName().endsWith(".docx")) {
            if (!fileName.toLowerCase().endsWith(".docx")) {
                fileName += ".docx";
            }
            saveToDocxBanRo(new File(fileName));
        } else if (selectedFile.getName().endsWith(".txt")) {
            if (!fileName.toLowerCase().endsWith(".txt")) {
                fileName += ".txt";
            }
            saveToTxtBanRo(new File(fileName));
        }
    }
    }//GEN-LAST:event_btnLuuBanRoActionPerformed

    private void txtBanMa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBanMa1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBanMa1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Elgamal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Elgamal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Elgamal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Elgamal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Elgamal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAuto;
    private javax.swing.JButton btnGiaiMa;
    private javax.swing.JButton btnGuiBanMa;
    private javax.swing.JButton btnLuuBanMa;
    private javax.swing.JButton btnLuuBanRo;
    private javax.swing.JButton btnMaHoa;
    private javax.swing.JButton btnTaoKhoa;
    private javax.swing.JButton btnXoa;
    private javax.swing.JButton btnXoaBanMa;
    private javax.swing.JButton btnXoaBanRo;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField txtA;
    private javax.swing.JTextField txtAlpha;
    private javax.swing.JTextField txtBanMa1;
    private javax.swing.JTextField txtBanMa2;
    private javax.swing.JTextField txtBanRo1;
    private javax.swing.JTextField txtBanRo2;
    private javax.swing.JTextField txtBeta;
    private javax.swing.JTextField txtK;
    private javax.swing.JTextField txtP;
    // End of variables declaration//GEN-END:variables
}
